SELECT
	sum(VALUE) AS VALUE 
	, CASE ONLINE_OR_IN_PERSON WHEN 1 THEN 'Online' WHEN 2 THEN 'In-Person' ELSE 'Error' END AS ONLINE_OR_IN_PERSON 
	, DATE_PART('quarter', to_date(TRANSACTION_DATE,'DD/MM/YYYY HH24:MI:SS')) AS QUARTER
FROM
	TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01 
WHERE TRANSACTION_CODE LIKE 'DSB%'
GROUP BY Quarter, ONLINE_OR_IN_PERSON
