SELECT *
, SPLIT_part(TRANSACTION_CODE,'-',1) AS Bank
, CASE 
	WHEN ONLINE_OR_IN_PERSON = 1 THEN 'Online'
	WHEN ONLINE_OR_IN_PERSON = 2 THEN 'In-Person'
END
, to_date(TRANSACTION_DATE,'DD/MM/YY HH24:MI:SS') AS DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01 
LIMIT 10